export const INSIGHT_MOCKS = [
  {
    id: 1,
    user: 'Jose M.',
    avatarUrl: '/mocks/avatar-jose.jpg',
    text: 'The aperitivo scene in Navigli was absolutely magical in winter. The heated terraces, warm cocktails, and canal views created the perfect atmosphere for our evening out.',
    timeAgo: '2 days',
    rating: 5,
    locationText: 'Navigli Social Club',
    label: 'Verified' as const,
    likes: 24,
  },
  {
    id: 2,
    user: 'Emma K.',
    avatarUrl: '/mocks/avatar-alessandra.jpg',
    text: 'The Christmas markets were enchanting! Hot chocolate, beautiful crafts, and the festive atmosphere made our Milano winter trip unforgettable.',
    timeAgo: '3 days',
    rating: 4,
    locationText: 'Christmas Markets',
    label: 'Verified' as const,
    likes: 35,
  },
  {
    id: 3,
    user: 'Marco T.',
    avatarUrl: '/mocks/avatar-james.jpg',
    text: '“Osteria del Borgo exceeded all expectations. The truffle risotto was phenomenal, and the cozy atmosphere made it perfect for a winter dinner date.',
    timeAgo: '1 week',
    rating: 4.5,
    locationText: 'Osteria del Borgo',
    label: 'Tourist' as const,
    likes: 18,
  },
];
